const API_BASE_URL_DEVELOPMENT = 'https://localhost:7011'
const API_BASE_URL_PRODUCTION = 'https://appname.azurestaticapps.net'

const ENDPOINTS = {
	GET_ALL_JOBS: 'jobs',
	GET_JOB_BY_ID: 'jobs',
	CREATE_JOB: 'jobs-create',
	UPDATE_JOB: 'jobs-update',
	DELETE_JOB: 'jobs-delete',
}

const DEVELOPMENT = {
	API_URL_GET_ALL_JOBS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_JOBS}`,
	API_URL_GET_JOB_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_JOBS}`,
	API_URL_CREATE_JOB: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_JOB}`,
	API_URL_UPADATE_JOB: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_JOB}`,
	API_URL_DELETE_JOB: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_JOB}`,
}

const PRODUCTION = {
	API_URL_GET_ALL_JOBS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_JOBS}`,
	API_URL_GET_JOB_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_JOBS}`,
	API_URL_CREATE_JOB: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_JOB}`,
	API_URL_UPADATE_JOB: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_JOB}`,
	API_URL_DELETE_JOB: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_JOB}`,
}

const Constants =
	process.env.NODE_ENV === 'development' ? DEVELOPMENT : PRODUCTION

export default Constants
