// <auto-generated />
using JobBoardServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBoardServer.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("JobBoardServer.Data.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description of job 1",
                            Title = "Job1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description of job 2",
                            Title = "Job2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description of job 3",
                            Title = "Job3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description of job 4",
                            Title = "Job4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description of job 5",
                            Title = "Job5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
